# Generated by Django 2.0.7 on 2018-07-09 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whoami', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_ipstart', models.IntegerField()),
                ('_ipend', models.IntegerField()),
                ('autonomous_system_organization', models.CharField(max_length=255)),
            ],
        ),
    ]
