# Generated by Django 2.0.7 on 2018-07-10 03:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('whoami', '0002_asn'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asn',
            old_name='_ipend',
            new_name='ip_end',
        ),
        migrations.RenameField(
            model_name='asn',
            old_name='_ipstart',
            new_name='ip_start',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='_ipend',
            new_name='ip_end',
        ),
        migrations.RenameField(
            model_name='block',
            old_name='_ipstart',
            new_name='ip_start',
        ),
    ]
