# Generated by Django 2.0.7 on 2018-09-17 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_start', models.IntegerField()),
                ('ip_end', models.IntegerField()),
                ('autonomous_system_organization', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_start', models.IntegerField()),
                ('ip_end', models.IntegerField()),
                ('geoname_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geoname_id', models.IntegerField()),
                ('continent_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('city_name', models.CharField(max_length=255)),
            ],
        ),
    ]
