# Generated by Django 4.2.4 on 2023-08-27 16:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AsnBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipv4', models.BooleanField(default=True)),
                ('ip_start', models.DecimalField(decimal_places=0, max_digits=39)),
                ('ip_end', models.DecimalField(decimal_places=0, max_digits=39)),
                ('autonomous_system_organization', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CityBlock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ipv4', models.BooleanField(default=True)),
                ('ip_start', models.DecimalField(decimal_places=0, max_digits=39)),
                ('ip_end', models.DecimalField(decimal_places=0, max_digits=39)),
                ('geoname_id', models.IntegerField()),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='CityLocation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('geoname_id', models.IntegerField()),
                ('continent_name', models.CharField(max_length=256)),
                ('country_name', models.CharField(max_length=256)),
                ('city_name', models.CharField(max_length=256)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
            ],
        ),
    ]
